FROM ubuntu:latest

RUN apt-get -y  update 

RUN apt-get -y install git

RUN mkdir ~/devops02

RUN git clone https://github.com/InzynieriaOprogramowaniaAGH/MDO2023_INO.git ~/devops02

RUN echo "Skopiowano repozytorium"

